"""Sum the even fibonacci numbers < 4 000 000
n;upper bound;int
#Fibonacci
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def run(n):
    return sum(attempt_1(n))


def attempt_1(n):
    fib = [0, 1]
    while fib[-1] < n:
        fib.append(fib[-1] + fib[-2])
    return [i for i in fib if i%2==0]

if __name__ == '__main__':
    print(run(4*10**6))
